pipeline:
  test:
    image: ruby:2.2.2
    environment:
      - RAILS_ENV=test
    script:
      - sleep 5
      - echo "lok"
      - bundle install
      - bundle exec rspec spec
services:
  database:
    image: mysql
  redis:
    image: redis