pipeline:
  ruby_build:
    image: ruby:2.2.2
    environment:
      - RAILS_ENV=test
    commands:
      - bundle install
      - bundle exec rake db:migrate
      - bundle exec rake db:seed
      - bundle exec rspec spec
  notify:
    image: drillster/drone-email
    commands:
      - echo $${EMAIL_HOST}
      - echo $${EMAIL_USER_NAME}
      - echo $${EMAIL_PASSWORD}
    host: $${EMAIL_HOST}
    port: 2525
    username: $${EMAIL_USER_NAME}
    password: $${EMAIL_PASSWORD}
    authentication: plain
    enable_starttls_auto: true
    from: messages@voonik.com
    recipients: [naveen.s@voonik.com, lokanadham.m@voonik.com]
    secrets: [ email_host, email_port, email_user_name, email_password ]
services:
  database:
    image: mysql:5.7.14   
    environment:
      - MYSQL_DATABASE=assessment_service
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  redis:
    image: redis