pipeline:
  ruby_build:
    image: ruby:2.2.2
    environment:
      - RAILS_ENV=test
  notify:
    webhook:
      image: plugins/webhook
      urls: https://api.flock.com/hooks/sendMessage/7cdb68f6-b2ca-4703-8529-e445b89aa5cc
      debug: true
      template: |
        '{
          "text" : "{ \n \"owner\": \"{{ repo.owner }}\", \n \"repo\": \"{{ repo.name }}\", \"build_number\": \"{{build.number}}\", \"commit\": \"{{ build.commit }}\", \"branch\": \"{{ build.branch }}\", \"message\": \"{{ build.message }}\", \"author\": \"{{ build.author }}\", \"status\": \"{{ build.status }}\", \"link\": \"{{build.link}}\" }"
        }'

services:
  database:
    image: mysql:5.7.14   
    environment:
      - MYSQL_DATABASE=assessment_service
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  redis:
    image: redis