pipeline:
  build:
    image: ruby:2.2.2
    environment:
      - RAILS_ENV=test
    script:
      - sleep 15
      - mkdir -p /tmp/bundler
      - sudo chown ubuntu:ubuntu /tmp/bundler
      - bundle install --path=/tmp/bundler --deployment --quiet
      - bundle exec rspec spec
services:
  database:
    image: mysql
    environment:
      - MYSQL_DATABASE=assessment_service
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  redis:
    image: redis
cache:
  - /tmp/bundler
notify:
  email:
    recipients:
      - naveen.s@voonik.com