pipeline:
  ruby_build:
    image: ruby:2.2.2
    environment:
      - RAILS_ENV=test
    commands:
      - bundle install
      - bundle exec rake db:migrate
      - bundle exec rake db:seed
      - bundle exec rspec spec
  notify:
    image: drillster/drone-email
    from: messages@voonik.com
    recipients: [naveen.s@voonik.com, lokanadham.m@voonik.com]
    secrets: [EMAIL_HOST, EMAIL_PORT, EMAIL_USERNAME, EMAIL_PASSWORD]
  webhook:
    image: plugins/webhook
    urls: https://api.flock.com/hooks/sendMessage/7cdb68f6-b2ca-4703-8529-e445b89aa5cc
    content_type: application/json
    template: |
      {
        "build_number": "{{build.number}}",
        "owner": "{{ repo.owner }}",
        "repo": "{{ repo.name }}",
        "branch": "{{ commit.branch }}",
        "message": "{{ commit.message }}",
        "author": "{{ commit.author.name }}",
        "commit sha": "{{ commit.SHA }}",
        "status": "{{ build.status }}",
      }

services:
  database:
    image: mysql:5.7.14   
    environment:
      - MYSQL_DATABASE=assessment_service
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  redis:
    image: redis