pipeline:
  ruby_build:
    image: ruby:2.2.2
    environment:
      - RAILS_ENV=test
    commands:
      - echo $HOST_DETAILS
      - echo $${HOST_DETAILS}
      - bundle install
      - bundle exec rake db:migrate
      - bundle exec rake db:seed
      - bundle exec rspec spec
    secrets: [ host_details ]
services:
  database:
    image: mysql:5.7.14   
    environment:
      - MYSQL_DATABASE=assessment_service
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  redis:
    image: redis