pipeline:
  ruby_build:
    image: ruby:2.2.2
    environment:
      - RAILS_ENV=test
    commands:
      - echo $HOST_DETAILS
      - echo $${HOST_DETAILS}
      - bundle install
      - bundle exec rake db:migrate
      - bundle exec rake db:seed
      - bundle exec rspec spec
    secrets: [ host_details ]
  notify:
    image: drillster/drone-email
    host: $${email_host}
    port: $${email_port}
    username: $${email_user_name}
    password: $${email_password}
    from: messages@voonik.com
    recipients: [naveen.s@voonik.com, lokanadham.m@voonik.com]
services:
  database:
    image: mysql:5.7.14   
    environment:
      - MYSQL_DATABASE=assessment_service
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  redis:
    image: redis