pipeline:
  ruby_build:
    image: ruby:2.2.2
    environment:
      - RAILS_ENV=test
    commands:
      - sleep 5
      - bundle install
      - bundle exec rspec spec
services:
  database:
    image: mysql    
    environment:
      - MYSQL_DATABASE=assessment_service
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  redis:
    image: redis