pipeline:
  build:
    image: ruby:2.2.2
    environment:
      - RAILS_ENV=test
    commands:
      - sleep 5
      - bundle install
      - bundle exec rspec spec
services:
  database:
    image: mysql
  redis:
    image: redis