pipeline:
  ruby_build:
    image: ruby:2.2.2
    environment:
      - RAILS_ENV=test
  notify:
    image: drillster/drone-email
    from: messages@voonik.com
    recipients: [naveen.s@voonik.com, lokanadham.m@voonik.com]
    secrets: [EMAIL_HOST, EMAIL_PORT, EMAIL_USERNAME, EMAIL_PASSWORD]
  webhook:
    image: plugins/webhook
    secrets: [WEBHOOK_URLS]
    debug: true
    content_type: application/json
    template: |
      {
        "text" : "{ \n\t \"owner\": \"{{ repo.owner }}\", \n\t \"repo\": \"{{ repo.name }}\", \n\t \"build_number\": \"{{build.number}}\", \n\t \"commit\": \"{{ build.commit }}\", \n\t \"branch\": \"{{ build.branch }}\",\n\t \"message\": \"{{ build.message }}\", \n\t \"author\": \"{{ build.author }}\", \n\t \"status\": \"{{ build.status }}\",\n\t \"link\": \"{{build.link}}\" }"
      }

services:
  database:
    image: mysql:5.7.14   
    environment:
      - MYSQL_DATABASE=assessment_service
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  redis:
    image: redis