development:
  adapter: mysql2
  host: "localhost"
  port: 3306
  username: "root"
  password: ""
  database: assessment_service

test:
  adapter: mysql2
  host: database
  port: 3306
  username: "root"
  password: ""
  database: assessment_service